### ISSUE TITLE
History rewriting is breaking Go modules

### ISSUE THREAD

**Issue by Sean-Der** [marten-seemann/qtls#1]
Hey!

We have a Go implementation of WebRTC [pions/webrtc](https://github.com/pions/webrtc) and are using quic-go (which is working amazingly!) but keep getting breakage because of history rewriting in this repo.

I think it just happened today, but with go modules I am getting `go: github.com/marten-seemann/qtls@v0.0.0-20190110111248-7a090b30c3ab: unknown revision 7a090b30c3ab`

Am I pinning to the wrong commits, any suggestions on what I should be doing here?

thanks!

**Comment by Sean-Der** [comment]
I moved my issue to to the quic-go repo https://github.com/lucas-clemente/quic-go/issues/1781

**Comment by marten-seemann** [comment]
I rewrite the history in order to keep the diff to the underlying TLS implementation small. Had I not done that over the last couple of months, switching from tls-tris to the standard library implementation would have been **a lot** more difficult.
We're currently not using gomod in quic-go, so I'm not very familiar with how it works. Do you think this problem would be solved if we adopt gomod in quic-go?

**Comment by Sean-Der** [comment]
That would be awesome if you could use modules!

I can set it up if that is helpful. The `vendor` directory is ignored by modules, so I don't think anyone who has `GO111MODULES=on` can use `quic-go` currently

**Comment by marten-seemann** [comment]
I’ll have a look at go modules once we make the transition to Go 1.12, which will happen very soon.

**Comment by Sean-Der** [comment]
Awesome, thank you so much @marten-seemann 

Would it be ok if I opened a PR to make qtls work with go-quic in the short term (or go-quic with qtls)? It can be on a different branch, doesn't have to be the tip etc...

I just need two SHAs that are available via git that work together. If not I totally understand, I just can't get my builds great until that happens.

thanks

**Comment by marten-seemann** [comment]
There's still the pending PR here: https://github.com/lucas-clemente/quic-go/pull/1780. This one needs to be merged first, then I'll have a look at go mod. Not sure if we'll do that right away though, we might wait for the Go 1.12 release. Not decided yet.

**Comment by marten-seemann** [comment]
The old hash should still exist in this repo, if that helps: https://github.com/marten-seemann/qtls-deprecated.

**Comment by Sean-Der** [comment]
Oh nice, that should work perfectly! Thanks for all the help @marten-seemann
