### ISSUE TITLE
E:\go\src\github.com\marten-seemann\qtls\common.go:1076:20: undefined: cpu.ARM64

### ISSUE THREAD

**Issue by coolskys** [marten-seemann/qtls#10]
When i tried to build go-micro without gomodule on, I got this error,;if it is neccessary to set this?

My go environment:
E:\go\src\go_micro>go env
set GO111MODULE=off
set GOARCH=amd64
set GOBIN=D:\Go\bin
set GOCACHE=D:\AppData\Local\go-build
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=E:\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build690395166=/tmp/go-build -gno-record-gcc-switches

**Comment by marten-seemann** [comment]
It's not intended to be used without Go modules.
