### ISSUE TITLE
Plans for Go version support in the future?

### ISSUE THREAD

**Issue by thepaul** [marten-seemann/qtls#11]
Could you give some indication of your plans for support of Go versions?

I see that support for Go 1.13 was removed several weeks before Go 1.15 was released. That might suggest that you only intend to support the latest Go release, although perhaps Go 1.13 was a special case because of the large number of extra build-tagged files it required.

(We're hoping we can expect to have things keep working for at least the three latest major versions, other than 1.13.)

**Comment by marten-seemann** [comment]
In accordance with the Go release policy, we support the 2 most recent major versions.

Note that for qtls, the code for every Go version will be located in a separate repository, which is with the release of Go 1.16 this repo here will be marked as deprecated.
