### ISSUE TITLE
"This commit breaks the build"

### ISSUE THREAD

**Issue by xlab** [marten-seemann/qtls#2]
Hi, not sure why this is needed
https://github.com/marten-seemann/qtls/commit/370e4627c8caa227a4e1743d4ac6bb76167fc196

That breaks the latest https://github.com/ipfs/go-ipfs builds.

**Comment by marten-seemann** [comment]
Go-ipfs doesn’t use qtls, so I don’t know why it would break the build. This repo is only used by quic-go, which uses Go mod, so this shouldn’t be a problem either.

**Comment by ghost** [comment]
Not sure why you said that ipfs doesn't use this, if you think about it really hard, ipfs uses quic-go which uses qtls. Are you just trying to be a jerk? Cause that function doesn't exist.

**Comment by jbenet** [comment]
@tomgie that's an unacceptable way to treat anybody on github. Please be more respectful, especially to helpful authors who try to maintain packages for others' use, for free, and who try to provide support on issues.
