### ISSUE TITLE
lack of "crypto/ed25519" file

### ISSUE THREAD

**Issue by Hicck** [marten-seemann/qtls#8]
Tag 4.0, missing the "crypto/ed25519" file at auth.go，
..\..\marten-seemann\qtls\auth.go:11:2: cannot find package "crypto/ed25519"

**Comment by klaasel** [comment]
Actually I had this problem when updating qtls to the latest master today. I changed the imports as a workaround to "golang.org/x/crypto/ed25519"

**Comment by fabiofcferreira** [comment]
@marten-seemann I don't have crypto/ed25519 but I do have it inside `golang.org/x` external package folder. What about a PR changing the import path to that of external packages?

**Comment by dmalykh** [comment]
From https://godoc.org/golang.org/x/crypto/ed25519 "Beginning with Go 1.13, the functionality of this package was moved to the standard library as crypto/ed25519." 

Just upgrade to Go 1.13.

**Comment by fabiofcferreira** [comment]
Alright. Looks like I was running an older version. It wasn't older than 1 month though. Thank you so much @dmalykh
