### ISSUE TITLE
Doesn't build on Go 1.12

### ISSUE THREAD

**Issue by calmh** [marten-seemann/qtls#9]
This package uses `crypto/ed25519` which was added in Go 1.13. The older name `golang.org/x/crypto/ed25519` still works and ends up being a wrapper for the same package when build with Go 1.13+. Would you consider using the older name for a while longer?

(*I* use Go 1.13, but our stuff gets included in various Linux distros and such and they're not always super quick to upgrade to the latest compiler, etc.)

**Comment by marten-seemann** [comment]
quic-go also requires Go 1.13, therefore I don't see any reason to support Go 1.12 any longer.

**Comment by calmh** [comment]
How so? This is the only compile failure that prevents quic-go from building on Go 1.12.

**Comment by marten-seemann** [comment]
That's currently true, but I don't think it would be a good idea to stop using new features just to support some outdated Linux distributions.
